// Regenerates src/generated/api.d.ts from the live OpenAPI spec.
//
//   bun run generate                      # http://localhost:3000/api/spec.json
//   SPEC_URL=http://localhost:3100/api/spec.json bun run generate
//
// The spec is served by the Vigilator app itself, so a dev server must be
// running (`bun run dev:no-auth` in the app repo). The output is committed:
// consumers of the package never run this.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const specUrl = process.env.SPEC_URL ?? "http://localhost:3000/api/spec.json";
const output = resolve(import.meta.dirname, "../src/generated/api.d.ts");

let ast: Awaited<ReturnType<typeof openapiTS>>;
try {
	ast = await openapiTS(new URL(specUrl), {
		alphabetize: true,
		exportType: true,
	});
} catch (error) {
	console.error(`Could not generate types from ${specUrl}.`);
	console.error(
		"Is a Vigilator dev server running? Start one with `bun run dev:no-auth` in the app repo, or point SPEC_URL at another instance.",
	);
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
}

const banner = [
	"// generated by scripts/generate-types.ts - do not edit by hand.",
	`//   source:    ${specUrl}`,
	`//   timestamp: ${new Date().toISOString()}`,
	"",
	"",
].join("\n");

await mkdir(dirname(output), { recursive: true });
await writeFile(output, banner + astToString(ast));
console.log(`Wrote ${output}`);
